// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9zZ0F17V0b3LTuH_qlrwZwQiEENkYHT0',
    appId: '1:83352469322:web:0779509e5b739fcf43cbb3',
    messagingSenderId: '83352469322',
    projectId: 'matchatea-app',
    authDomain: 'matchatea-app.firebaseapp.com',
    storageBucket: 'matchatea-app.firebasestorage.app',
    measurementId: 'G-SLT6MJSTJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-e9vgZ3PqHYblyDS4E5XzB8uzE4tApI',
    appId: '1:83352469322:android:20f52d1965c3d11443cbb3',
    messagingSenderId: '83352469322',
    projectId: 'matchatea-app',
    storageBucket: 'matchatea-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9zZ0F17V0b3LTuH_qlrwZwQiEENkYHT0',
    appId: '1:83352469322:web:890fbf44acf38ab943cbb3',
    messagingSenderId: '83352469322',
    projectId: 'matchatea-app',
    authDomain: 'matchatea-app.firebaseapp.com',
    storageBucket: 'matchatea-app.firebasestorage.app',
    measurementId: 'G-QC6WXNQ0LS',
  );
}
